:- consult('vocabulary/defend.pl').
:- consult('vocabulary/direction.pl').
:- consult('vocabulary/dodge.pl').
:- consult('vocabulary/fire.pl').
:- consult('vocabulary/grass.pl').
:- consult('vocabulary/intensity.pl').
:- consult('vocabulary/move.pl').
:- consult('vocabulary/normal.pl').
:- consult('vocabulary/subject.pl').
:- consult('vocabulary/water.pl').
:- consult('vocabulary/electric.pl').