% Defend words
defend_words([
    'resist',
    'defend',
    'shield',
    'fortify',
    'endure',
    'hold out',
    'stand',
    'protect',
    'guard',
    'cover',
    'reinforce',
    'secure',
    'strengthen',
    'harden',
    'brace',
    'block',
    'ward off',
    'fight off',
    'parry',
    'safeguard',
    'uphold',
    'preserve',
    'resilient',
    'withstand',
    'fend off',
    'repel',
    'repulse',
    'resolute',
    'stave off',
    'deflect',
    'keep at bay'
]).