% Intensity types

% STRONG
intensity_type('strongly', strong).
intensity_type('strong', strong).
intensity_type('powerfully', strong).
intensity_type('powerful', strong).
intensity_type('heavily', strong).
intensity_type('heavy', strong).
intensity_type('drastically', strong).
intensity_type('drastic', strong).
intensity_type('seriously', strong).
intensity_type('serious', strong).
intensity_type('extremely', strong).
intensity_type('extreme', strong).
intensity_type('forcefully', strong).
intensity_type('forceful', strong).
intensity_type('intensely', strong).
intensity_type('intense', strong).
intensity_type('energetically', strong).
intensity_type('energetic', strong).
intensity_type('vigorously', strong).
intensity_type('vigorous', strong).
intensity_type('potently', strong).
intensity_type('potent', strong).
intensity_type('fiercely', strong).
intensity_type('fierce', strong).
intensity_type('hard', strong).
intensity_type('mightily', strong).
intensity_type('mighty', strong).
intensity_type('robustly', strong).
intensity_type('robust', strong).
intensity_type('sturdily', strong).
intensity_type('sturdy', strong).
intensity_type('vehemently', strong).
intensity_type('vehement', strong).
intensity_type('vividly', strong).
intensity_type('vivid', strong).
intensity_type('staunchly', strong).
intensity_type('staunch', strong).
intensity_type('turbulently', strong).
intensity_type('turbulent', strong).


% WEAK
intensity_type('weakly', weak).
intensity_type('weak', weak).
intensity_type('a little', weak).
intensity_type('little', weak).
intensity_type('somewhat', weak).
intensity_type('a bit', weak).
intensity_type('bit', weak).
intensity_type('softly', weak).
intensity_type('soft', weak).
intensity_type('gently', weak).
intensity_type('gentle', weak).
intensity_type('slightly', weak).
intensity_type('slight', weak).
intensity_type('mildly', weak).
intensity_type('mild', weak).
intensity_type('barely', weak).
intensity_type('faintly', weak).
intensity_type('faint', weak).
intensity_type('meagerly', weak).
intensity_type('meager', weak).
intensity_type('moderately', weak).
intensity_type('moderate', weak).
intensity_type('feebly', weak).
intensity_type('feeble', weak).
intensity_type('timidly', weak).
intensity_type('timid', weak).
intensity_type('sparingly', weak).
intensity_type('sparing', weak).
intensity_type('hesitantly', weak).
intensity_type('hesitant', weak).