past_tense(throw, threw).
past_tense(use, used).
past_tense(kick, kicked).
past_tense(hit, hit).
past_tense(slash, slashed).
past_tense(destroy, destroyed).
past_tense(burn, burned).
past_tense(freeze, froze).
past_tense(shoot, shot).
past_tense(fight, fought).
past_tense(bite, bit).
past_tense(cut, cut).
past_tense(strike, struck).
past_tense(beat, beat).
past_tense(attack, attacked).
past_tense(punch, punched).
past_tense(smash, smashed).
past_tense(push, pushed).
past_tense(pull, pulled).
past_tense(toss, tossed).
past_tense(grab, grabbed).
past_tense(break, broke).
past_tense(hurl, hurled).
past_tense(knock, knocked).
past_tense(drag, dragged).
past_tense(sling, slung).
past_tense(slam, slammed).
past_tense(jab, jabbed).
past_tense(stab, stabbed).
past_tense(whack, whacked).
past_tense(bash, bashed).
past_tense(whip, whipped).
past_tense(launch, launched).
past_tense(explode, exploded).
past_tense(erupt, erupted).
past_tense(squeeze, squeezed).
past_tense(crush, crushed).
past_tense(clash, clashed).
past_tense(spin, spun).
past_tense(swipe, swiped).
past_tense(fling, flung).
past_tense(ram, rammed).
past_tense(blast, blasted).
past_tense(dash, dashed).
past_tense(charge, charged).
past_tense(stomp, stomped).
past_tense(trample, trampled).
past_tense(lunge, lunged).
past_tense(barrage, barraged).
past_tense(barricade, barricaded).
past_tense(pelt, pelted).
past_tense(bombard, bombarded).
past_tense(assault, assaulted).
past_tense(besiege, besieged).
past_tense(ambush, ambushed).
past_tense(clobber, clobbered).
past_tense(mangle, mangled).
past_tense(maul, mauled).
past_tense(ravage, ravaged).
past_tense(pillage, pillaged).
past_tense(plunder, plundered).
past_tense(sack, sacked).
past_tense(ransack, ransacked).
past_tense(devastate, devastated).
past_tense(decimate, decimated).
past_tense(annihilate, annihilated).
past_tense(obliterate, obliterated).
past_tense(vanquish, vanquished).
past_tense(subdue, subdued).
past_tense(subjugate, subjugated).
past_tense(capture, captured).
past_tense(envelop, enveloped).
past_tense(overwhelm, overwhelmed).
past_tense(overcome, overcame).
past_tense(surmount, surmounted).
past_tense(conquer, conquered).
past_tense(triumph, triumphed).
past_tense(defeat, defeated).
past_tense(overpower, overpowered).
past_tense(overthrow, overthrew).
past_tense(oust, ousted).
past_tense(expel, expelled).
past_tense(banish, banished).
past_tense(eject, ejected).
past_tense(evict, evicted).
past_tense(displace, displaced).
past_tense(dethrone, dethroned).
past_tense(depose, deposed).
past_tense(supplant, supplanted).
past_tense(dispossess, dispossessed).
past_tense(repel, repelled).
past_tense(repulse, repulsed).
past_tense(thwart, thwarted).
past_tense(foil, foiled).
past_tense(fracture, fractured).
past_tense(fragment, fragmented).
past_tense(disintegrate, disintegrated).
past_tense(shatter, shattered).
past_tense(smatter, smattered).
past_tense(splinter, splintered).
past_tense(crack, cracked).
past_tense(rupture, ruptured).
past_tense(burn, burned).
past_tense(incinerate, incinerated).
past_tense(combust, combusted).
past_tense(glow, glowed).
past_tense(drain, drained).
past_tense(bloom, bloomed).
past_tense(shrub, shrubbed).
past_tense(pump, pumped).
past_tense(splash, splashed).
past_tense(rain, rained).
past_tense(pee, peed).
past_tense(pour, poured).
past_tense(spray, sprayed).
past_tense(flood, flooded).
past_tense(move, moved).
past_tense(run, ran).
past_tense(walk, walked).
past_tense(go, went).
past_tense(step, stepped).
past_tense(stroll, strolled).
past_tense(jog, jogged).
past_tense(sprint, sprinted).
past_tense(dash, dashed).
past_tense(hurry, hurried).
past_tense(advance, advanced).
past_tense(proceed, proceeded).
past_tense(march, marched).
past_tense(traverse, traversed).
past_tense(wander, wandered).
past_tense(amble, ambled).
past_tense(stride, strode).
past_tense(gallop, galloped).
past_tense(hike, hiked).
past_tense(scuttle, scuttled).
past_tense(skip, skipped).
past_tense(hop, hopped).
past_tense(leap, leaped).
past_tense(bound, bounded).
past_tense(travel, traveled).
past_tense(navigate, navigated).
past_tense(journey, journeyed).
past_tense(avoid, avoided).
past_tense(evade, evaded).
past_tense(dodge, dodged).
past_tense(jump, jumped).
past_tense(care, cared).
past_tense(sidestep, sidestepped).
past_tense(elude, eluded).
past_tense(escape, escaped).
past_tense(swerve, swerved).
past_tense(shift, shifted).
past_tense(skirt, skirted).
past_tense(bypass, bypassed).
past_tense(duck, ducked).
past_tense(flee, fled).
past_tense(retreat, retreated).
past_tense(recoil, recoiled).
past_tense(resist, resisted).
past_tense(defend, defended).
past_tense(shield, shielded).
past_tense(fortify, fortified).
past_tense(endure, endured).
past_tense(hold, held).
past_tense(stand, stood).
past_tense(protect, protected).
past_tense(guard, guarded).
past_tense(cover, covered).
past_tense(reinforce, reinforced).
past_tense(secure, secured).
past_tense(strengthen, strengthened).
past_tense(harden, hardened).
past_tense(brace, braced).
past_tense(block, blocked).
past_tense(parry, parried).
past_tense(safeguard, safeguarded).
past_tense(uphold, upheld).
past_tense(preserve, preserved).
past_tense(withstand, withstood).
past_tense(repulse, repulsed).
past_tense(deflect, deflected).

